//! Written manually. Also in hlsdk but I write it manually

#![allow(unused, nonstandard_style, deref_nullptr, clippy::upper_case_acronyms)]

use std::os::raw::*;
use std::ptr::NonNull;

use crate::hooks::engine::{client_sprite_s, rect_s, SCREENINFO};

#[repr(C)]
pub struct cl_enginefuncs_s {
    pub pfnSPR_Load: unsafe extern "C" fn(*const c_char) -> c_int,
    pub pfnSPR_Frames: NonNull<c_void>,
    pub pfnSPR_Height: NonNull<c_void>,
    pub pfnSPR_Width: NonNull<c_void>,
    pub pfnSPR_Set: unsafe extern "C" fn(c_int, c_int, c_int, c_int),
    pub pfnSPR_Draw: NonNull<c_void>,
    pub pfnSPR_DrawHoles: NonNull<c_void>,
    pub pfnSPR_DrawAdditive: unsafe extern "C" fn(c_int, c_int, c_int, *const rect_s),
    pub pfnSPR_EnableScissor: NonNull<c_void>,
    pub pfnSPR_DisableScissor: NonNull<c_void>,
    pub pfnSPR_GetList: unsafe extern "C" fn(*const c_char, *mut c_int) -> *mut client_sprite_s,
    pub pfnFillRGBA: unsafe extern "C" fn(c_int, c_int, c_int, c_int, c_int, c_int, c_int, c_int),
    pub pfnGetScreenInfo: unsafe extern "C" fn(*mut SCREENINFO) -> c_int,
    pub pfnSetCrosshair: NonNull<c_void>,
    pub pfnRegisterVariable: NonNull<c_void>,
    pub pfnGetCvarFloat: NonNull<c_void>,
    pub pfnGetCvarString: NonNull<c_void>,
    pub pfnAddCommand: NonNull<c_void>,
    pub pfnHookUserMsg: NonNull<c_void>,
    pub pfnServerCmd: NonNull<c_void>,
    pub pfnClientCmd: NonNull<c_void>,
    pub pfnGetPlayerInfo: NonNull<c_void>,
    pub pfnPlaySoundByName: NonNull<c_void>,
    pub pfnPlaySoundByIndex: NonNull<c_void>,
    pub pfnAngleVectors: NonNull<c_void>,
    pub pfnTextMessageGet: NonNull<c_void>,
    pub pfnDrawCharacter: NonNull<c_void>,
    pub pfnDrawConsoleString: NonNull<c_void>,
    pub pfnDrawSetTextColor: NonNull<c_void>,
    pub pfnDrawConsoleStringLen: NonNull<c_void>,
    pub pfnConsolePrint: NonNull<c_void>,
    pub pfnCenterPrint: NonNull<c_void>,
    pub GetWindowCenterX: NonNull<c_void>,
    pub GetWindowCenterY: NonNull<c_void>,
    pub GetViewAngles: NonNull<c_void>,
    pub SetViewAngles: NonNull<c_void>,
    pub GetMaxClients: NonNull<c_void>,
    pub Cvar_SetValue: NonNull<c_void>,
    pub Cmd_Argc: NonNull<c_void>,
    pub Cmd_Argv: NonNull<c_void>,
    pub Con_Printf: NonNull<c_void>,
    pub Con_DPrintf: NonNull<c_void>,
    pub Con_NPrintf: NonNull<c_void>,
    pub Con_NXPrintf: NonNull<c_void>,
    pub PhysInfo_ValueForKey: NonNull<c_void>,
    pub ServerInfo_ValueForKey: NonNull<c_void>,
    pub GetClientMaxspeed: NonNull<c_void>,
    pub CheckParm: NonNull<c_void>,
    pub Key_Event: NonNull<c_void>,
    pub GetMousePosition: NonNull<c_void>,
    pub IsNoClipping: NonNull<c_void>,
    pub GetLocalPlayer: NonNull<c_void>,
    pub GetViewModel: NonNull<c_void>,
    pub GetEntityByIndex: NonNull<c_void>,
    pub GetClientTime: NonNull<c_void>,
    pub V_CalcShake: NonNull<c_void>,
    pub V_ApplyShake: NonNull<c_void>,
    pub PM_PointContents: NonNull<c_void>,
    pub PM_WaterEntity: NonNull<c_void>,
    pub PM_TraceLine: NonNull<c_void>,
    pub CL_LoadModel: NonNull<c_void>,
    pub CL_CreateVisibleEntity: NonNull<c_void>,
    pub GetSpritePointer: NonNull<c_void>,
    pub pfnPlaySoundByNameAtLocation: NonNull<c_void>,
    pub pfnPrecacheEvent: NonNull<c_void>,
    pub pfnPlaybackEvent: NonNull<c_void>,
    pub pfnWeaponAnim: NonNull<c_void>,
    pub pfnRandomFloat: NonNull<c_void>,
    pub pfnRandomLong: NonNull<c_void>,
    pub pfnHookEvent: NonNull<c_void>,
    pub Con_IsVisible: NonNull<c_void>,
    pub pfnGetGameDirectory: NonNull<c_void>,
    pub pfnGetCvarPointer: NonNull<c_void>,
    pub Key_LookupBinding: NonNull<c_void>,
    pub pfnGetLevelName: NonNull<c_void>,
    pub pfnGetScreenFade: NonNull<c_void>,
    pub pfnSetScreenFade: NonNull<c_void>,
    pub VGui_GetPanel: NonNull<c_void>,
    pub VGui_ViewportPaintBackground: NonNull<c_void>,
    pub COM_LoadFile: NonNull<c_void>,
    pub COM_ParseFile: NonNull<c_void>,
    pub COM_FreeFile: NonNull<c_void>,
    pub pTriAPI: NonNull<c_void>,
    pub pEfxAPI: NonNull<c_void>,
    pub pEventAPI: NonNull<c_void>,
    pub pDemoAPI: NonNull<c_void>,
    pub pNetAPI: NonNull<c_void>,
    pub pVoiceTweak: NonNull<c_void>,
    pub IsSpectateOnly: NonNull<c_void>,
    pub LoadMapSprite: NonNull<c_void>,
    pub COM_AddAppDirectoryToSearchPath: NonNull<c_void>,
    pub COM_ExpandFilename: NonNull<c_void>,
    pub PlayerInfo_ValueForKey: NonNull<c_void>,
    pub PlayerInfo_SetValueForKey: NonNull<c_void>,
    pub GetPlayerUniqueID: NonNull<c_void>,
    pub GetTrackerIDForPlayer: NonNull<c_void>,
    pub GetPlayerForTrackerID: NonNull<c_void>,
    pub pfnServerCmdUnreliable: NonNull<c_void>,
    pub pfnGetMousePos: NonNull<c_void>,
    pub pfnSetMousePos: NonNull<c_void>,
    pub pfnSetMouseEnable: NonNull<c_void>,
    pub GetFirstCvarPtr: NonNull<c_void>,
    pub GetFirstCmdFunctionHandle: NonNull<c_void>,
    pub GetNextCmdFunctionHandle: NonNull<c_void>,
    pub GetCmdFunctionName: NonNull<c_void>,
    pub hudGetClientOldTime: NonNull<c_void>,
    pub hudGetServerGravityValue: NonNull<c_void>,
    pub hudGetModelByIndex: NonNull<c_void>,
    pub pfnSetFilterMode: NonNull<c_void>,
    pub pfnSetFilterColor: NonNull<c_void>,
    pub pfnSetFilterBrightness: NonNull<c_void>,
    pub pfnSequenceGet: NonNull<c_void>,
    pub pfnSPR_DrawGeneric: NonNull<c_void>,
    pub pfnSequencePickSentence: NonNull<c_void>,
    pub pfnDrawString: NonNull<c_void>,
    pub pfnDrawStringReverse: NonNull<c_void>,
    pub LocalPlayerInfo_ValueForKey: NonNull<c_void>,
    pub pfnVGUI2DrawCharacter: NonNull<c_void>,
    pub pfnVGUI2DrawCharacterAdd: NonNull<c_void>,
    pub COM_GetApproxWavePlayLength: NonNull<c_void>,
    pub pfnGetCareerUI: NonNull<c_void>,
    pub Cvar_Set: NonNull<c_void>,
    pub pfnIsCareerMatch: NonNull<c_void>,
    pub pfnPlaySoundVoiceByName: NonNull<c_void>,
    pub pfnPrimeMusicStream: NonNull<c_void>,
    pub GetAbsoluteTime: NonNull<c_void>,
    pub pfnProcessTutorMessageDecayBuffer: NonNull<c_void>,
    pub pfnConstructTutorMessageDecayBuffer: NonNull<c_void>,
    pub pfnResetTutorMessageDecayData: NonNull<c_void>,
    pub pfnPlaySoundByNameAtPitch: NonNull<c_void>,
    pub pfnFillRGBABlend: NonNull<c_void>,
    pub pfnGetAppID: NonNull<c_void>,
    pub pfnGetAliasList: NonNull<c_void>,
    pub pfnVguiWrap2_GetMouseDelta: NonNull<c_void>,
    pub pfnFilteredClientCmd: NonNull<c_void>,
}
