// bindgen common/event_api.h --allowlist-type "event_api_s" -- --target=i686-unknown-linux-gnu
// -I{public,common,engine,pm_shared} -include common/mathlib.h -include common/const.h
// then add the clippy allow
// then add `use std::os::raw::*;`

#![allow(unused, nonstandard_style, deref_nullptr)]
use std::os::raw::*;

/* automatically generated by rust-bindgen 0.71.1 */

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct edict_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct event_api_s {
    pub version: c_int,
    pub EV_PlaySound: Option<
        unsafe extern "C" fn(
            ent: c_int,
            origin: *mut f32,
            channel: c_int,
            sample: *const c_char,
            volume: f32,
            attenuation: f32,
            fFlags: c_int,
            pitch: c_int,
        ),
    >,
    pub EV_StopSound:
        Option<unsafe extern "C" fn(ent: c_int, channel: c_int, sample: *const c_char)>,
    pub EV_FindModelIndex: Option<unsafe extern "C" fn(pmodel: *const c_char) -> c_int>,
    pub EV_IsLocal: Option<unsafe extern "C" fn(playernum: c_int) -> c_int>,
    pub EV_LocalPlayerDucking: Option<unsafe extern "C" fn() -> c_int>,
    pub EV_LocalPlayerViewheight: Option<unsafe extern "C" fn(arg1: *mut f32)>,
    pub EV_LocalPlayerBounds:
        Option<unsafe extern "C" fn(hull: c_int, mins: *mut f32, maxs: *mut f32)>,
    pub EV_IndexFromTrace: Option<unsafe extern "C" fn(pTrace: *mut pmtrace_s) -> c_int>,
    pub EV_GetPhysent: Option<unsafe extern "C" fn(idx: c_int) -> *mut physent_s>,
    pub EV_SetUpPlayerPrediction:
        Option<unsafe extern "C" fn(dopred: c_int, bIncludeLocalClient: c_int)>,
    pub EV_PushPMStates: Option<unsafe extern "C" fn()>,
    pub EV_PopPMStates: Option<unsafe extern "C" fn()>,
    pub EV_SetSolidPlayers: Option<unsafe extern "C" fn(playernum: c_int)>,
    pub EV_SetTraceHull: Option<unsafe extern "C" fn(hull: c_int)>,
    pub EV_PlayerTrace: Option<
        unsafe extern "C" fn(
            start: *mut f32,
            end: *mut f32,
            traceFlags: c_int,
            ignore_pe: c_int,
            tr: *mut pmtrace_s,
        ),
    >,
    pub EV_WeaponAnimation: Option<unsafe extern "C" fn(sequence: c_int, body: c_int)>,
    pub EV_PrecacheEvent:
        Option<unsafe extern "C" fn(type_: c_int, psz: *const c_char) -> c_ushort>,
    pub EV_PlaybackEvent: Option<
        unsafe extern "C" fn(
            flags: c_int,
            pInvoker: *const edict_s,
            eventindex: c_ushort,
            delay: f32,
            origin: *mut f32,
            angles: *mut f32,
            fparam1: f32,
            fparam2: f32,
            iparam1: c_int,
            iparam2: c_int,
            bparam1: c_int,
            bparam2: c_int,
        ),
    >,
    pub EV_TraceTexture: Option<
        unsafe extern "C" fn(ground: c_int, vstart: *mut f32, vend: *mut f32) -> *const c_char,
    >,
    pub EV_StopAllSounds: Option<unsafe extern "C" fn(entnum: c_int, entchannel: c_int)>,
    pub EV_KillEvents: Option<unsafe extern "C" fn(entnum: c_int, eventname: *const c_char)>,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of event_api_s"][::std::mem::size_of::<event_api_s>() - 88usize];
    ["Alignment of event_api_s"][::std::mem::align_of::<event_api_s>() - 4usize];
    ["Offset of field: event_api_s::version"]
        [::std::mem::offset_of!(event_api_s, version) - 0usize];
    ["Offset of field: event_api_s::EV_PlaySound"]
        [::std::mem::offset_of!(event_api_s, EV_PlaySound) - 4usize];
    ["Offset of field: event_api_s::EV_StopSound"]
        [::std::mem::offset_of!(event_api_s, EV_StopSound) - 8usize];
    ["Offset of field: event_api_s::EV_FindModelIndex"]
        [::std::mem::offset_of!(event_api_s, EV_FindModelIndex) - 12usize];
    ["Offset of field: event_api_s::EV_IsLocal"]
        [::std::mem::offset_of!(event_api_s, EV_IsLocal) - 16usize];
    ["Offset of field: event_api_s::EV_LocalPlayerDucking"]
        [::std::mem::offset_of!(event_api_s, EV_LocalPlayerDucking) - 20usize];
    ["Offset of field: event_api_s::EV_LocalPlayerViewheight"]
        [::std::mem::offset_of!(event_api_s, EV_LocalPlayerViewheight) - 24usize];
    ["Offset of field: event_api_s::EV_LocalPlayerBounds"]
        [::std::mem::offset_of!(event_api_s, EV_LocalPlayerBounds) - 28usize];
    ["Offset of field: event_api_s::EV_IndexFromTrace"]
        [::std::mem::offset_of!(event_api_s, EV_IndexFromTrace) - 32usize];
    ["Offset of field: event_api_s::EV_GetPhysent"]
        [::std::mem::offset_of!(event_api_s, EV_GetPhysent) - 36usize];
    ["Offset of field: event_api_s::EV_SetUpPlayerPrediction"]
        [::std::mem::offset_of!(event_api_s, EV_SetUpPlayerPrediction) - 40usize];
    ["Offset of field: event_api_s::EV_PushPMStates"]
        [::std::mem::offset_of!(event_api_s, EV_PushPMStates) - 44usize];
    ["Offset of field: event_api_s::EV_PopPMStates"]
        [::std::mem::offset_of!(event_api_s, EV_PopPMStates) - 48usize];
    ["Offset of field: event_api_s::EV_SetSolidPlayers"]
        [::std::mem::offset_of!(event_api_s, EV_SetSolidPlayers) - 52usize];
    ["Offset of field: event_api_s::EV_SetTraceHull"]
        [::std::mem::offset_of!(event_api_s, EV_SetTraceHull) - 56usize];
    ["Offset of field: event_api_s::EV_PlayerTrace"]
        [::std::mem::offset_of!(event_api_s, EV_PlayerTrace) - 60usize];
    ["Offset of field: event_api_s::EV_WeaponAnimation"]
        [::std::mem::offset_of!(event_api_s, EV_WeaponAnimation) - 64usize];
    ["Offset of field: event_api_s::EV_PrecacheEvent"]
        [::std::mem::offset_of!(event_api_s, EV_PrecacheEvent) - 68usize];
    ["Offset of field: event_api_s::EV_PlaybackEvent"]
        [::std::mem::offset_of!(event_api_s, EV_PlaybackEvent) - 72usize];
    ["Offset of field: event_api_s::EV_TraceTexture"]
        [::std::mem::offset_of!(event_api_s, EV_TraceTexture) - 76usize];
    ["Offset of field: event_api_s::EV_StopAllSounds"]
        [::std::mem::offset_of!(event_api_s, EV_StopAllSounds) - 80usize];
    ["Offset of field: event_api_s::EV_KillEvents"]
        [::std::mem::offset_of!(event_api_s, EV_KillEvents) - 84usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmtrace_s {
    _unused: [u8; 0],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct physent_s {
    pub _address: u8,
}
