// bindgen common/r_efx.h --allowlist-type "efx_api_s" -- --target=i686-unknown-linux-gnu
// -I{public,common,engine,pm_shared} -include common/mathlib.h -include common/const.h
// then add the clippy allow
// then add `use std::os::raw::*;`

#![allow(unused, nonstandard_style, deref_nullptr)]
use std::os::raw::*;

use crate::ffi::com_model::model_s;

/* automatically generated by rust-bindgen 0.71.1 */

#[doc = "\tCopyright (c) 1996-2002, Valve LLC. All rights reserved.\n\n\tThis product contains software technology licensed from Id\n\tSoftware, Inc. (\"Id Technology\").  Id Technology (c) 1996 Id Software, Inc.\n\tAll Rights Reserved.\n\n   Use, distribution, and modification of this source code and/or resulting\n   object code is restricted to non-commercial enhancements to products from\n   Valve LLC.  All other use, distribution, or modification is prohibited\n   without written permission from Valve LLC."]
pub type vec_t = f32;
pub type vec3_t = [vec_t; 3usize];
pub type byte = c_uchar;
pub const qboolean_false_: qboolean = 0;
pub const qboolean_true_: qboolean = 1;
pub type qboolean = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct color24 {
    pub r: byte,
    pub g: byte,
    pub b: byte,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of color24"][::std::mem::size_of::<color24>() - 3usize];
    ["Alignment of color24"][::std::mem::align_of::<color24>() - 1usize];
    ["Offset of field: color24::r"][::std::mem::offset_of!(color24, r) - 0usize];
    ["Offset of field: color24::g"][::std::mem::offset_of!(color24, g) - 1usize];
    ["Offset of field: color24::b"][::std::mem::offset_of!(color24, b) - 2usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct colorVec {
    pub r: c_uint,
    pub g: c_uint,
    pub b: c_uint,
    pub a: c_uint,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of colorVec"][::std::mem::size_of::<colorVec>() - 16usize];
    ["Alignment of colorVec"][::std::mem::align_of::<colorVec>() - 4usize];
    ["Offset of field: colorVec::r"][::std::mem::offset_of!(colorVec, r) - 0usize];
    ["Offset of field: colorVec::g"][::std::mem::offset_of!(colorVec, g) - 4usize];
    ["Offset of field: colorVec::b"][::std::mem::offset_of!(colorVec, b) - 8usize];
    ["Offset of field: colorVec::a"][::std::mem::offset_of!(colorVec, a) - 12usize];
};
pub const ptype_t_pt_static: ptype_t = 0;
pub const ptype_t_pt_grav: ptype_t = 1;
pub const ptype_t_pt_slowgrav: ptype_t = 2;
pub const ptype_t_pt_fire: ptype_t = 3;
pub const ptype_t_pt_explode: ptype_t = 4;
pub const ptype_t_pt_explode2: ptype_t = 5;
pub const ptype_t_pt_blob: ptype_t = 6;
pub const ptype_t_pt_blob2: ptype_t = 7;
pub const ptype_t_pt_vox_slowgrav: ptype_t = 8;
pub const ptype_t_pt_vox_grav: ptype_t = 9;
pub const ptype_t_pt_clientcustom: ptype_t = 10;
pub type ptype_t = c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct particle_s {
    pub org: vec3_t,
    pub color: c_short,
    pub packedColor: c_short,
    pub next: *mut particle_s,
    pub vel: vec3_t,
    pub ramp: f32,
    pub die: f32,
    pub type_: ptype_t,
    pub deathfunc: Option<unsafe extern "C" fn(particle: *mut particle_s)>,
    pub callback: Option<unsafe extern "C" fn(particle: *mut particle_s, frametime: f32)>,
    pub context: c_uchar,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of particle_s"][::std::mem::size_of::<particle_s>() - 56usize];
    ["Alignment of particle_s"][::std::mem::align_of::<particle_s>() - 4usize];
    ["Offset of field: particle_s::org"][::std::mem::offset_of!(particle_s, org) - 0usize];
    ["Offset of field: particle_s::color"][::std::mem::offset_of!(particle_s, color) - 12usize];
    ["Offset of field: particle_s::packedColor"]
        [::std::mem::offset_of!(particle_s, packedColor) - 14usize];
    ["Offset of field: particle_s::next"][::std::mem::offset_of!(particle_s, next) - 16usize];
    ["Offset of field: particle_s::vel"][::std::mem::offset_of!(particle_s, vel) - 20usize];
    ["Offset of field: particle_s::ramp"][::std::mem::offset_of!(particle_s, ramp) - 32usize];
    ["Offset of field: particle_s::die"][::std::mem::offset_of!(particle_s, die) - 36usize];
    ["Offset of field: particle_s::type_"][::std::mem::offset_of!(particle_s, type_) - 40usize];
    ["Offset of field: particle_s::deathfunc"]
        [::std::mem::offset_of!(particle_s, deathfunc) - 44usize];
    ["Offset of field: particle_s::callback"]
        [::std::mem::offset_of!(particle_s, callback) - 48usize];
    ["Offset of field: particle_s::context"][::std::mem::offset_of!(particle_s, context) - 52usize];
};
pub type particle_t = particle_s;
pub type BEAM = beam_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct beam_s {
    pub next: *mut BEAM,
    pub type_: c_int,
    pub flags: c_int,
    pub source: vec3_t,
    pub target: vec3_t,
    pub delta: vec3_t,
    pub t: f32,
    pub freq: f32,
    pub die: f32,
    pub width: f32,
    pub amplitude: f32,
    pub r: f32,
    pub g: f32,
    pub b: f32,
    pub brightness: f32,
    pub speed: f32,
    pub frameRate: f32,
    pub frame: f32,
    pub segments: c_int,
    pub startEntity: c_int,
    pub endEntity: c_int,
    pub modelIndex: c_int,
    pub frameCount: c_int,
    pub pFollowModel: *mut model_s,
    pub particles: *mut particle_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of beam_s"][::std::mem::size_of::<beam_s>() - 124usize];
    ["Alignment of beam_s"][::std::mem::align_of::<beam_s>() - 4usize];
    ["Offset of field: beam_s::next"][::std::mem::offset_of!(beam_s, next) - 0usize];
    ["Offset of field: beam_s::type_"][::std::mem::offset_of!(beam_s, type_) - 4usize];
    ["Offset of field: beam_s::flags"][::std::mem::offset_of!(beam_s, flags) - 8usize];
    ["Offset of field: beam_s::source"][::std::mem::offset_of!(beam_s, source) - 12usize];
    ["Offset of field: beam_s::target"][::std::mem::offset_of!(beam_s, target) - 24usize];
    ["Offset of field: beam_s::delta"][::std::mem::offset_of!(beam_s, delta) - 36usize];
    ["Offset of field: beam_s::t"][::std::mem::offset_of!(beam_s, t) - 48usize];
    ["Offset of field: beam_s::freq"][::std::mem::offset_of!(beam_s, freq) - 52usize];
    ["Offset of field: beam_s::die"][::std::mem::offset_of!(beam_s, die) - 56usize];
    ["Offset of field: beam_s::width"][::std::mem::offset_of!(beam_s, width) - 60usize];
    ["Offset of field: beam_s::amplitude"][::std::mem::offset_of!(beam_s, amplitude) - 64usize];
    ["Offset of field: beam_s::r"][::std::mem::offset_of!(beam_s, r) - 68usize];
    ["Offset of field: beam_s::g"][::std::mem::offset_of!(beam_s, g) - 72usize];
    ["Offset of field: beam_s::b"][::std::mem::offset_of!(beam_s, b) - 76usize];
    ["Offset of field: beam_s::brightness"][::std::mem::offset_of!(beam_s, brightness) - 80usize];
    ["Offset of field: beam_s::speed"][::std::mem::offset_of!(beam_s, speed) - 84usize];
    ["Offset of field: beam_s::frameRate"][::std::mem::offset_of!(beam_s, frameRate) - 88usize];
    ["Offset of field: beam_s::frame"][::std::mem::offset_of!(beam_s, frame) - 92usize];
    ["Offset of field: beam_s::segments"][::std::mem::offset_of!(beam_s, segments) - 96usize];
    ["Offset of field: beam_s::startEntity"]
        [::std::mem::offset_of!(beam_s, startEntity) - 100usize];
    ["Offset of field: beam_s::endEntity"][::std::mem::offset_of!(beam_s, endEntity) - 104usize];
    ["Offset of field: beam_s::modelIndex"][::std::mem::offset_of!(beam_s, modelIndex) - 108usize];
    ["Offset of field: beam_s::frameCount"][::std::mem::offset_of!(beam_s, frameCount) - 112usize];
    ["Offset of field: beam_s::pFollowModel"]
        [::std::mem::offset_of!(beam_s, pFollowModel) - 116usize];
    ["Offset of field: beam_s::particles"][::std::mem::offset_of!(beam_s, particles) - 120usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct dlight_s {
    pub origin: vec3_t,
    pub radius: f32,
    pub color: color24,
    pub die: f32,
    pub decay: f32,
    pub minlight: f32,
    pub key: c_int,
    pub dark: qboolean,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of dlight_s"][::std::mem::size_of::<dlight_s>() - 40usize];
    ["Alignment of dlight_s"][::std::mem::align_of::<dlight_s>() - 4usize];
    ["Offset of field: dlight_s::origin"][::std::mem::offset_of!(dlight_s, origin) - 0usize];
    ["Offset of field: dlight_s::radius"][::std::mem::offset_of!(dlight_s, radius) - 12usize];
    ["Offset of field: dlight_s::color"][::std::mem::offset_of!(dlight_s, color) - 16usize];
    ["Offset of field: dlight_s::die"][::std::mem::offset_of!(dlight_s, die) - 20usize];
    ["Offset of field: dlight_s::decay"][::std::mem::offset_of!(dlight_s, decay) - 24usize];
    ["Offset of field: dlight_s::minlight"][::std::mem::offset_of!(dlight_s, minlight) - 28usize];
    ["Offset of field: dlight_s::key"][::std::mem::offset_of!(dlight_s, key) - 32usize];
    ["Offset of field: dlight_s::dark"][::std::mem::offset_of!(dlight_s, dark) - 36usize];
};
pub type dlight_t = dlight_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct efrag_s {
    pub leaf: *mut mleaf_s,
    pub leafnext: *mut efrag_s,
    pub entity: *mut cl_entity_s,
    pub entnext: *mut efrag_s,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of efrag_s"][::std::mem::size_of::<efrag_s>() - 16usize];
    ["Alignment of efrag_s"][::std::mem::align_of::<efrag_s>() - 4usize];
    ["Offset of field: efrag_s::leaf"][::std::mem::offset_of!(efrag_s, leaf) - 0usize];
    ["Offset of field: efrag_s::leafnext"][::std::mem::offset_of!(efrag_s, leafnext) - 4usize];
    ["Offset of field: efrag_s::entity"][::std::mem::offset_of!(efrag_s, entity) - 8usize];
    ["Offset of field: efrag_s::entnext"][::std::mem::offset_of!(efrag_s, entnext) - 12usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mouth_t {
    pub mouthopen: byte,
    pub sndcount: byte,
    pub sndavg: c_int,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of mouth_t"][::std::mem::size_of::<mouth_t>() - 8usize];
    ["Alignment of mouth_t"][::std::mem::align_of::<mouth_t>() - 4usize];
    ["Offset of field: mouth_t::mouthopen"][::std::mem::offset_of!(mouth_t, mouthopen) - 0usize];
    ["Offset of field: mouth_t::sndcount"][::std::mem::offset_of!(mouth_t, sndcount) - 1usize];
    ["Offset of field: mouth_t::sndavg"][::std::mem::offset_of!(mouth_t, sndavg) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct latchedvars_t {
    pub prevanimtime: f32,
    pub sequencetime: f32,
    pub prevseqblending: [byte; 2usize],
    pub prevorigin: vec3_t,
    pub prevangles: vec3_t,
    pub prevsequence: c_int,
    pub prevframe: f32,
    pub prevcontroller: [byte; 4usize],
    pub prevblending: [byte; 2usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of latchedvars_t"][::std::mem::size_of::<latchedvars_t>() - 52usize];
    ["Alignment of latchedvars_t"][::std::mem::align_of::<latchedvars_t>() - 4usize];
    ["Offset of field: latchedvars_t::prevanimtime"]
        [::std::mem::offset_of!(latchedvars_t, prevanimtime) - 0usize];
    ["Offset of field: latchedvars_t::sequencetime"]
        [::std::mem::offset_of!(latchedvars_t, sequencetime) - 4usize];
    ["Offset of field: latchedvars_t::prevseqblending"]
        [::std::mem::offset_of!(latchedvars_t, prevseqblending) - 8usize];
    ["Offset of field: latchedvars_t::prevorigin"]
        [::std::mem::offset_of!(latchedvars_t, prevorigin) - 12usize];
    ["Offset of field: latchedvars_t::prevangles"]
        [::std::mem::offset_of!(latchedvars_t, prevangles) - 24usize];
    ["Offset of field: latchedvars_t::prevsequence"]
        [::std::mem::offset_of!(latchedvars_t, prevsequence) - 36usize];
    ["Offset of field: latchedvars_t::prevframe"]
        [::std::mem::offset_of!(latchedvars_t, prevframe) - 40usize];
    ["Offset of field: latchedvars_t::prevcontroller"]
        [::std::mem::offset_of!(latchedvars_t, prevcontroller) - 44usize];
    ["Offset of field: latchedvars_t::prevblending"]
        [::std::mem::offset_of!(latchedvars_t, prevblending) - 48usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct position_history_t {
    pub animtime: f32,
    pub origin: vec3_t,
    pub angles: vec3_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of position_history_t"][::std::mem::size_of::<position_history_t>() - 28usize];
    ["Alignment of position_history_t"][::std::mem::align_of::<position_history_t>() - 4usize];
    ["Offset of field: position_history_t::animtime"]
        [::std::mem::offset_of!(position_history_t, animtime) - 0usize];
    ["Offset of field: position_history_t::origin"]
        [::std::mem::offset_of!(position_history_t, origin) - 4usize];
    ["Offset of field: position_history_t::angles"]
        [::std::mem::offset_of!(position_history_t, angles) - 16usize];
};
pub type cl_entity_t = cl_entity_s;
pub type entity_state_t = entity_state_s;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct entity_state_s {
    pub entityType: c_int,
    pub number: c_int,
    pub msg_time: f32,
    pub messagenum: c_int,
    pub origin: vec3_t,
    pub angles: vec3_t,
    pub modelindex: c_int,
    pub sequence: c_int,
    pub frame: f32,
    pub colormap: c_int,
    pub skin: c_short,
    pub solid: c_short,
    pub effects: c_int,
    pub scale: f32,
    pub eflags: byte,
    pub rendermode: c_int,
    pub renderamt: c_int,
    pub rendercolor: color24,
    pub renderfx: c_int,
    pub movetype: c_int,
    pub animtime: f32,
    pub framerate: f32,
    pub body: c_int,
    pub controller: [byte; 4usize],
    pub blending: [byte; 4usize],
    pub velocity: vec3_t,
    pub mins: vec3_t,
    pub maxs: vec3_t,
    pub aiment: c_int,
    pub owner: c_int,
    pub friction: f32,
    pub gravity: f32,
    pub team: c_int,
    pub playerclass: c_int,
    pub health: c_int,
    pub spectator: qboolean,
    pub weaponmodel: c_int,
    pub gaitsequence: c_int,
    pub basevelocity: vec3_t,
    pub usehull: c_int,
    pub oldbuttons: c_int,
    pub onground: c_int,
    pub iStepLeft: c_int,
    pub flFallVelocity: f32,
    pub fov: f32,
    pub weaponanim: c_int,
    pub startpos: vec3_t,
    pub endpos: vec3_t,
    pub impacttime: f32,
    pub starttime: f32,
    pub iuser1: c_int,
    pub iuser2: c_int,
    pub iuser3: c_int,
    pub iuser4: c_int,
    pub fuser1: f32,
    pub fuser2: f32,
    pub fuser3: f32,
    pub fuser4: f32,
    pub vuser1: vec3_t,
    pub vuser2: vec3_t,
    pub vuser3: vec3_t,
    pub vuser4: vec3_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of entity_state_s"][::std::mem::size_of::<entity_state_s>() - 340usize];
    ["Alignment of entity_state_s"][::std::mem::align_of::<entity_state_s>() - 4usize];
    ["Offset of field: entity_state_s::entityType"]
        [::std::mem::offset_of!(entity_state_s, entityType) - 0usize];
    ["Offset of field: entity_state_s::number"]
        [::std::mem::offset_of!(entity_state_s, number) - 4usize];
    ["Offset of field: entity_state_s::msg_time"]
        [::std::mem::offset_of!(entity_state_s, msg_time) - 8usize];
    ["Offset of field: entity_state_s::messagenum"]
        [::std::mem::offset_of!(entity_state_s, messagenum) - 12usize];
    ["Offset of field: entity_state_s::origin"]
        [::std::mem::offset_of!(entity_state_s, origin) - 16usize];
    ["Offset of field: entity_state_s::angles"]
        [::std::mem::offset_of!(entity_state_s, angles) - 28usize];
    ["Offset of field: entity_state_s::modelindex"]
        [::std::mem::offset_of!(entity_state_s, modelindex) - 40usize];
    ["Offset of field: entity_state_s::sequence"]
        [::std::mem::offset_of!(entity_state_s, sequence) - 44usize];
    ["Offset of field: entity_state_s::frame"]
        [::std::mem::offset_of!(entity_state_s, frame) - 48usize];
    ["Offset of field: entity_state_s::colormap"]
        [::std::mem::offset_of!(entity_state_s, colormap) - 52usize];
    ["Offset of field: entity_state_s::skin"]
        [::std::mem::offset_of!(entity_state_s, skin) - 56usize];
    ["Offset of field: entity_state_s::solid"]
        [::std::mem::offset_of!(entity_state_s, solid) - 58usize];
    ["Offset of field: entity_state_s::effects"]
        [::std::mem::offset_of!(entity_state_s, effects) - 60usize];
    ["Offset of field: entity_state_s::scale"]
        [::std::mem::offset_of!(entity_state_s, scale) - 64usize];
    ["Offset of field: entity_state_s::eflags"]
        [::std::mem::offset_of!(entity_state_s, eflags) - 68usize];
    ["Offset of field: entity_state_s::rendermode"]
        [::std::mem::offset_of!(entity_state_s, rendermode) - 72usize];
    ["Offset of field: entity_state_s::renderamt"]
        [::std::mem::offset_of!(entity_state_s, renderamt) - 76usize];
    ["Offset of field: entity_state_s::rendercolor"]
        [::std::mem::offset_of!(entity_state_s, rendercolor) - 80usize];
    ["Offset of field: entity_state_s::renderfx"]
        [::std::mem::offset_of!(entity_state_s, renderfx) - 84usize];
    ["Offset of field: entity_state_s::movetype"]
        [::std::mem::offset_of!(entity_state_s, movetype) - 88usize];
    ["Offset of field: entity_state_s::animtime"]
        [::std::mem::offset_of!(entity_state_s, animtime) - 92usize];
    ["Offset of field: entity_state_s::framerate"]
        [::std::mem::offset_of!(entity_state_s, framerate) - 96usize];
    ["Offset of field: entity_state_s::body"]
        [::std::mem::offset_of!(entity_state_s, body) - 100usize];
    ["Offset of field: entity_state_s::controller"]
        [::std::mem::offset_of!(entity_state_s, controller) - 104usize];
    ["Offset of field: entity_state_s::blending"]
        [::std::mem::offset_of!(entity_state_s, blending) - 108usize];
    ["Offset of field: entity_state_s::velocity"]
        [::std::mem::offset_of!(entity_state_s, velocity) - 112usize];
    ["Offset of field: entity_state_s::mins"]
        [::std::mem::offset_of!(entity_state_s, mins) - 124usize];
    ["Offset of field: entity_state_s::maxs"]
        [::std::mem::offset_of!(entity_state_s, maxs) - 136usize];
    ["Offset of field: entity_state_s::aiment"]
        [::std::mem::offset_of!(entity_state_s, aiment) - 148usize];
    ["Offset of field: entity_state_s::owner"]
        [::std::mem::offset_of!(entity_state_s, owner) - 152usize];
    ["Offset of field: entity_state_s::friction"]
        [::std::mem::offset_of!(entity_state_s, friction) - 156usize];
    ["Offset of field: entity_state_s::gravity"]
        [::std::mem::offset_of!(entity_state_s, gravity) - 160usize];
    ["Offset of field: entity_state_s::team"]
        [::std::mem::offset_of!(entity_state_s, team) - 164usize];
    ["Offset of field: entity_state_s::playerclass"]
        [::std::mem::offset_of!(entity_state_s, playerclass) - 168usize];
    ["Offset of field: entity_state_s::health"]
        [::std::mem::offset_of!(entity_state_s, health) - 172usize];
    ["Offset of field: entity_state_s::spectator"]
        [::std::mem::offset_of!(entity_state_s, spectator) - 176usize];
    ["Offset of field: entity_state_s::weaponmodel"]
        [::std::mem::offset_of!(entity_state_s, weaponmodel) - 180usize];
    ["Offset of field: entity_state_s::gaitsequence"]
        [::std::mem::offset_of!(entity_state_s, gaitsequence) - 184usize];
    ["Offset of field: entity_state_s::basevelocity"]
        [::std::mem::offset_of!(entity_state_s, basevelocity) - 188usize];
    ["Offset of field: entity_state_s::usehull"]
        [::std::mem::offset_of!(entity_state_s, usehull) - 200usize];
    ["Offset of field: entity_state_s::oldbuttons"]
        [::std::mem::offset_of!(entity_state_s, oldbuttons) - 204usize];
    ["Offset of field: entity_state_s::onground"]
        [::std::mem::offset_of!(entity_state_s, onground) - 208usize];
    ["Offset of field: entity_state_s::iStepLeft"]
        [::std::mem::offset_of!(entity_state_s, iStepLeft) - 212usize];
    ["Offset of field: entity_state_s::flFallVelocity"]
        [::std::mem::offset_of!(entity_state_s, flFallVelocity) - 216usize];
    ["Offset of field: entity_state_s::fov"]
        [::std::mem::offset_of!(entity_state_s, fov) - 220usize];
    ["Offset of field: entity_state_s::weaponanim"]
        [::std::mem::offset_of!(entity_state_s, weaponanim) - 224usize];
    ["Offset of field: entity_state_s::startpos"]
        [::std::mem::offset_of!(entity_state_s, startpos) - 228usize];
    ["Offset of field: entity_state_s::endpos"]
        [::std::mem::offset_of!(entity_state_s, endpos) - 240usize];
    ["Offset of field: entity_state_s::impacttime"]
        [::std::mem::offset_of!(entity_state_s, impacttime) - 252usize];
    ["Offset of field: entity_state_s::starttime"]
        [::std::mem::offset_of!(entity_state_s, starttime) - 256usize];
    ["Offset of field: entity_state_s::iuser1"]
        [::std::mem::offset_of!(entity_state_s, iuser1) - 260usize];
    ["Offset of field: entity_state_s::iuser2"]
        [::std::mem::offset_of!(entity_state_s, iuser2) - 264usize];
    ["Offset of field: entity_state_s::iuser3"]
        [::std::mem::offset_of!(entity_state_s, iuser3) - 268usize];
    ["Offset of field: entity_state_s::iuser4"]
        [::std::mem::offset_of!(entity_state_s, iuser4) - 272usize];
    ["Offset of field: entity_state_s::fuser1"]
        [::std::mem::offset_of!(entity_state_s, fuser1) - 276usize];
    ["Offset of field: entity_state_s::fuser2"]
        [::std::mem::offset_of!(entity_state_s, fuser2) - 280usize];
    ["Offset of field: entity_state_s::fuser3"]
        [::std::mem::offset_of!(entity_state_s, fuser3) - 284usize];
    ["Offset of field: entity_state_s::fuser4"]
        [::std::mem::offset_of!(entity_state_s, fuser4) - 288usize];
    ["Offset of field: entity_state_s::vuser1"]
        [::std::mem::offset_of!(entity_state_s, vuser1) - 292usize];
    ["Offset of field: entity_state_s::vuser2"]
        [::std::mem::offset_of!(entity_state_s, vuser2) - 304usize];
    ["Offset of field: entity_state_s::vuser3"]
        [::std::mem::offset_of!(entity_state_s, vuser3) - 316usize];
    ["Offset of field: entity_state_s::vuser4"]
        [::std::mem::offset_of!(entity_state_s, vuser4) - 328usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct cl_entity_s {
    pub index: c_int,
    pub player: qboolean,
    pub baseline: entity_state_t,
    pub prevstate: entity_state_t,
    pub curstate: entity_state_t,
    pub current_position: c_int,
    pub ph: [position_history_t; 64usize],
    pub mouth: mouth_t,
    pub latched: latchedvars_t,
    pub lastmove: f32,
    pub origin: vec3_t,
    pub angles: vec3_t,
    pub attachment: [vec3_t; 4usize],
    pub trivial_accept: c_int,
    pub model: *mut model_s,
    pub efrag: *mut efrag_s,
    pub topnode: *mut mnode_s,
    pub syncbase: f32,
    pub visframe: c_int,
    pub cvFloorColor: colorVec,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of cl_entity_s"][::std::mem::size_of::<cl_entity_s>() - 3000usize];
    ["Alignment of cl_entity_s"][::std::mem::align_of::<cl_entity_s>() - 4usize];
    ["Offset of field: cl_entity_s::index"][::std::mem::offset_of!(cl_entity_s, index) - 0usize];
    ["Offset of field: cl_entity_s::player"][::std::mem::offset_of!(cl_entity_s, player) - 4usize];
    ["Offset of field: cl_entity_s::baseline"]
        [::std::mem::offset_of!(cl_entity_s, baseline) - 8usize];
    ["Offset of field: cl_entity_s::prevstate"]
        [::std::mem::offset_of!(cl_entity_s, prevstate) - 348usize];
    ["Offset of field: cl_entity_s::curstate"]
        [::std::mem::offset_of!(cl_entity_s, curstate) - 688usize];
    ["Offset of field: cl_entity_s::current_position"]
        [::std::mem::offset_of!(cl_entity_s, current_position) - 1028usize];
    ["Offset of field: cl_entity_s::ph"][::std::mem::offset_of!(cl_entity_s, ph) - 1032usize];
    ["Offset of field: cl_entity_s::mouth"][::std::mem::offset_of!(cl_entity_s, mouth) - 2824usize];
    ["Offset of field: cl_entity_s::latched"]
        [::std::mem::offset_of!(cl_entity_s, latched) - 2832usize];
    ["Offset of field: cl_entity_s::lastmove"]
        [::std::mem::offset_of!(cl_entity_s, lastmove) - 2884usize];
    ["Offset of field: cl_entity_s::origin"]
        [::std::mem::offset_of!(cl_entity_s, origin) - 2888usize];
    ["Offset of field: cl_entity_s::angles"]
        [::std::mem::offset_of!(cl_entity_s, angles) - 2900usize];
    ["Offset of field: cl_entity_s::attachment"]
        [::std::mem::offset_of!(cl_entity_s, attachment) - 2912usize];
    ["Offset of field: cl_entity_s::trivial_accept"]
        [::std::mem::offset_of!(cl_entity_s, trivial_accept) - 2960usize];
    ["Offset of field: cl_entity_s::model"][::std::mem::offset_of!(cl_entity_s, model) - 2964usize];
    ["Offset of field: cl_entity_s::efrag"][::std::mem::offset_of!(cl_entity_s, efrag) - 2968usize];
    ["Offset of field: cl_entity_s::topnode"]
        [::std::mem::offset_of!(cl_entity_s, topnode) - 2972usize];
    ["Offset of field: cl_entity_s::syncbase"]
        [::std::mem::offset_of!(cl_entity_s, syncbase) - 2976usize];
    ["Offset of field: cl_entity_s::visframe"]
        [::std::mem::offset_of!(cl_entity_s, visframe) - 2980usize];
    ["Offset of field: cl_entity_s::cvFloorColor"]
        [::std::mem::offset_of!(cl_entity_s, cvFloorColor) - 2984usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct tempent_s {
    pub flags: c_int,
    pub die: f32,
    pub frameMax: f32,
    pub x: f32,
    pub y: f32,
    pub z: f32,
    pub fadeSpeed: f32,
    pub bounceFactor: f32,
    pub hitSound: c_int,
    pub hitcallback: Option<unsafe extern "C" fn(ent: *mut tempent_s, ptr: *mut pmtrace_s)>,
    pub callback:
        Option<unsafe extern "C" fn(ent: *mut tempent_s, frametime: f32, currenttime: f32)>,
    pub next: *mut tempent_s,
    pub priority: c_int,
    pub clientIndex: c_short,
    pub tentOffset: vec3_t,
    pub entity: cl_entity_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of tempent_s"][::std::mem::size_of::<tempent_s>() - 3068usize];
    ["Alignment of tempent_s"][::std::mem::align_of::<tempent_s>() - 4usize];
    ["Offset of field: tempent_s::flags"][::std::mem::offset_of!(tempent_s, flags) - 0usize];
    ["Offset of field: tempent_s::die"][::std::mem::offset_of!(tempent_s, die) - 4usize];
    ["Offset of field: tempent_s::frameMax"][::std::mem::offset_of!(tempent_s, frameMax) - 8usize];
    ["Offset of field: tempent_s::x"][::std::mem::offset_of!(tempent_s, x) - 12usize];
    ["Offset of field: tempent_s::y"][::std::mem::offset_of!(tempent_s, y) - 16usize];
    ["Offset of field: tempent_s::z"][::std::mem::offset_of!(tempent_s, z) - 20usize];
    ["Offset of field: tempent_s::fadeSpeed"]
        [::std::mem::offset_of!(tempent_s, fadeSpeed) - 24usize];
    ["Offset of field: tempent_s::bounceFactor"]
        [::std::mem::offset_of!(tempent_s, bounceFactor) - 28usize];
    ["Offset of field: tempent_s::hitSound"][::std::mem::offset_of!(tempent_s, hitSound) - 32usize];
    ["Offset of field: tempent_s::hitcallback"]
        [::std::mem::offset_of!(tempent_s, hitcallback) - 36usize];
    ["Offset of field: tempent_s::callback"][::std::mem::offset_of!(tempent_s, callback) - 40usize];
    ["Offset of field: tempent_s::next"][::std::mem::offset_of!(tempent_s, next) - 44usize];
    ["Offset of field: tempent_s::priority"][::std::mem::offset_of!(tempent_s, priority) - 48usize];
    ["Offset of field: tempent_s::clientIndex"]
        [::std::mem::offset_of!(tempent_s, clientIndex) - 52usize];
    ["Offset of field: tempent_s::tentOffset"]
        [::std::mem::offset_of!(tempent_s, tentOffset) - 56usize];
    ["Offset of field: tempent_s::entity"][::std::mem::offset_of!(tempent_s, entity) - 68usize];
};
pub type TEMPENTITY = tempent_s;
#[repr(C)]
#[derive(Copy, Clone)]
pub struct efx_api_s {
    pub R_AllocParticle: Option<
        unsafe extern "C" fn(
            callback: Option<unsafe extern "C" fn(particle: *mut particle_s, frametime: f32)>,
        ) -> *mut particle_t,
    >,
    pub R_BlobExplosion: Option<unsafe extern "C" fn(org: *mut f32)>,
    pub R_Blood:
        Option<unsafe extern "C" fn(org: *mut f32, dir: *mut f32, pcolor: c_int, speed: c_int)>,
    pub R_BloodSprite: Option<
        unsafe extern "C" fn(
            org: *mut f32,
            colorindex: c_int,
            modelIndex: c_int,
            modelIndex2: c_int,
            size: f32,
        ),
    >,
    pub R_BloodStream:
        Option<unsafe extern "C" fn(org: *mut f32, dir: *mut f32, pcolor: c_int, speed: c_int)>,
    pub R_BreakModel: Option<
        unsafe extern "C" fn(
            pos: *mut f32,
            size: *mut f32,
            dir: *mut f32,
            random: f32,
            life: f32,
            count: c_int,
            modelIndex: c_int,
            flags: c_char,
        ),
    >,
    pub R_Bubbles: Option<
        unsafe extern "C" fn(
            mins: *mut f32,
            maxs: *mut f32,
            height: f32,
            modelIndex: c_int,
            count: c_int,
            speed: f32,
        ),
    >,
    pub R_BubbleTrail: Option<
        unsafe extern "C" fn(
            start: *mut f32,
            end: *mut f32,
            height: f32,
            modelIndex: c_int,
            count: c_int,
            speed: f32,
        ),
    >,
    pub R_BulletImpactParticles: Option<unsafe extern "C" fn(pos: *mut f32)>,
    pub R_EntityParticles: Option<unsafe extern "C" fn(ent: *mut cl_entity_s)>,
    pub R_Explosion: Option<
        unsafe extern "C" fn(pos: *mut f32, model: c_int, scale: f32, framerate: f32, flags: c_int),
    >,
    pub R_FizzEffect:
        Option<unsafe extern "C" fn(pent: *mut cl_entity_s, modelIndex: c_int, density: c_int)>,
    pub R_FireField: Option<
        unsafe extern "C" fn(
            org: *mut f32,
            radius: c_int,
            modelIndex: c_int,
            count: c_int,
            flags: c_int,
            life: f32,
        ),
    >,
    pub R_FlickerParticles: Option<unsafe extern "C" fn(org: *mut f32)>,
    pub R_FunnelSprite:
        Option<unsafe extern "C" fn(org: *mut f32, modelIndex: c_int, reverse: c_int)>,
    pub R_Implosion:
        Option<unsafe extern "C" fn(end: *mut f32, radius: f32, count: c_int, life: f32)>,
    pub R_LargeFunnel: Option<unsafe extern "C" fn(org: *mut f32, reverse: c_int)>,
    pub R_LavaSplash: Option<unsafe extern "C" fn(org: *mut f32)>,
    pub R_MultiGunshot: Option<
        unsafe extern "C" fn(
            org: *mut f32,
            dir: *mut f32,
            noise: *mut f32,
            count: c_int,
            decalCount: c_int,
            decalIndices: *mut c_int,
        ),
    >,
    pub R_MuzzleFlash: Option<unsafe extern "C" fn(pos1: *mut f32, type_: c_int)>,
    pub R_ParticleBox: Option<
        unsafe extern "C" fn(
            mins: *mut f32,
            maxs: *mut f32,
            r: c_uchar,
            g: c_uchar,
            b: c_uchar,
            life: f32,
        ),
    >,
    pub R_ParticleBurst:
        Option<unsafe extern "C" fn(pos: *mut f32, size: c_int, color: c_int, life: f32)>,
    pub R_ParticleExplosion: Option<unsafe extern "C" fn(org: *mut f32)>,
    pub R_ParticleExplosion2:
        Option<unsafe extern "C" fn(org: *mut f32, colorStart: c_int, colorLength: c_int)>,
    pub R_ParticleLine: Option<
        unsafe extern "C" fn(
            start: *mut f32,
            end: *mut f32,
            r: c_uchar,
            g: c_uchar,
            b: c_uchar,
            life: f32,
        ),
    >,
    pub R_PlayerSprites:
        Option<unsafe extern "C" fn(client: c_int, modelIndex: c_int, count: c_int, size: c_int)>,
    pub R_Projectile: Option<
        unsafe extern "C" fn(
            origin: *mut f32,
            velocity: *mut f32,
            modelIndex: c_int,
            life: c_int,
            owner: c_int,
            hitcallback: Option<unsafe extern "C" fn(ent: *mut tempent_s, ptr: *mut pmtrace_s)>,
        ),
    >,
    pub R_RicochetSound: Option<unsafe extern "C" fn(pos: *mut f32)>,
    pub R_RicochetSprite: Option<
        unsafe extern "C" fn(pos: *mut f32, pmodel: *mut model_s, duration: f32, scale: f32),
    >,
    pub R_RocketFlare: Option<unsafe extern "C" fn(pos: *mut f32)>,
    pub R_RocketTrail: Option<unsafe extern "C" fn(start: *mut f32, end: *mut f32, type_: c_int)>,
    pub R_RunParticleEffect:
        Option<unsafe extern "C" fn(org: *mut f32, dir: *mut f32, color: c_int, count: c_int)>,
    pub R_ShowLine: Option<unsafe extern "C" fn(start: *mut f32, end: *mut f32)>,
    pub R_SparkEffect: Option<
        unsafe extern "C" fn(pos: *mut f32, count: c_int, velocityMin: c_int, velocityMax: c_int),
    >,
    pub R_SparkShower: Option<unsafe extern "C" fn(pos: *mut f32)>,
    pub R_SparkStreaks: Option<
        unsafe extern "C" fn(pos: *mut f32, count: c_int, velocityMin: c_int, velocityMax: c_int),
    >,
    pub R_Spray: Option<
        unsafe extern "C" fn(
            pos: *mut f32,
            dir: *mut f32,
            modelIndex: c_int,
            count: c_int,
            speed: c_int,
            spread: c_int,
            rendermode: c_int,
        ),
    >,
    pub R_Sprite_Explode:
        Option<unsafe extern "C" fn(pTemp: *mut TEMPENTITY, scale: f32, flags: c_int)>,
    pub R_Sprite_Smoke: Option<unsafe extern "C" fn(pTemp: *mut TEMPENTITY, scale: f32)>,
    pub R_Sprite_Spray: Option<
        unsafe extern "C" fn(
            pos: *mut f32,
            dir: *mut f32,
            modelIndex: c_int,
            count: c_int,
            speed: c_int,
            iRand: c_int,
        ),
    >,
    pub R_Sprite_Trail: Option<
        unsafe extern "C" fn(
            type_: c_int,
            start: *mut f32,
            end: *mut f32,
            modelIndex: c_int,
            count: c_int,
            life: f32,
            size: f32,
            amplitude: f32,
            renderamt: c_int,
            speed: f32,
        ),
    >,
    pub R_Sprite_WallPuff: Option<unsafe extern "C" fn(pTemp: *mut TEMPENTITY, scale: f32)>,
    pub R_StreakSplash: Option<
        unsafe extern "C" fn(
            pos: *mut f32,
            dir: *mut f32,
            color: c_int,
            count: c_int,
            speed: f32,
            velocityMin: c_int,
            velocityMax: c_int,
        ),
    >,
    pub R_TracerEffect: Option<unsafe extern "C" fn(start: *mut f32, end: *mut f32)>,
    pub R_UserTracerParticle: Option<
        unsafe extern "C" fn(
            org: *mut f32,
            vel: *mut f32,
            life: f32,
            colorIndex: c_int,
            length: f32,
            deathcontext: c_uchar,
            deathfunc: Option<unsafe extern "C" fn(particle: *mut particle_s)>,
        ),
    >,
    pub R_TracerParticles:
        Option<unsafe extern "C" fn(org: *mut f32, vel: *mut f32, life: f32) -> *mut particle_t>,
    pub R_TeleportSplash: Option<unsafe extern "C" fn(org: *mut f32)>,
    pub R_TempSphereModel: Option<
        unsafe extern "C" fn(pos: *mut f32, speed: f32, life: f32, count: c_int, modelIndex: c_int),
    >,
    pub R_TempModel: Option<
        unsafe extern "C" fn(
            pos: *mut f32,
            dir: *mut f32,
            angles: *mut f32,
            life: f32,
            modelIndex: c_int,
            soundtype: c_int,
        ) -> *mut TEMPENTITY,
    >,
    pub R_DefaultSprite: Option<
        unsafe extern "C" fn(pos: *mut f32, spriteIndex: c_int, framerate: f32) -> *mut TEMPENTITY,
    >,
    pub R_TempSprite: Option<
        unsafe extern "C" fn(
            pos: *mut f32,
            dir: *mut f32,
            scale: f32,
            modelIndex: c_int,
            rendermode: c_int,
            renderfx: c_int,
            a: f32,
            life: f32,
            flags: c_int,
        ) -> *mut TEMPENTITY,
    >,
    pub Draw_DecalIndex: Option<unsafe extern "C" fn(id: c_int) -> c_int>,
    pub Draw_DecalIndexFromName: Option<unsafe extern "C" fn(name: *mut c_char) -> c_int>,
    pub R_DecalShoot: Option<
        unsafe extern "C" fn(
            textureIndex: c_int,
            entity: c_int,
            modelIndex: c_int,
            position: *mut f32,
            flags: c_int,
        ),
    >,
    pub R_AttachTentToPlayer:
        Option<unsafe extern "C" fn(client: c_int, modelIndex: c_int, zoffset: f32, life: f32)>,
    pub R_KillAttachedTents: Option<unsafe extern "C" fn(client: c_int)>,
    pub R_BeamCirclePoints: Option<
        unsafe extern "C" fn(
            type_: c_int,
            start: *mut f32,
            end: *mut f32,
            modelIndex: c_int,
            life: f32,
            width: f32,
            amplitude: f32,
            brightness: f32,
            speed: f32,
            startFrame: c_int,
            framerate: f32,
            r: f32,
            g: f32,
            b: f32,
        ) -> *mut BEAM,
    >,
    pub R_BeamEntPoint: Option<
        unsafe extern "C" fn(
            startEnt: c_int,
            end: *mut f32,
            modelIndex: c_int,
            life: f32,
            width: f32,
            amplitude: f32,
            brightness: f32,
            speed: f32,
            startFrame: c_int,
            framerate: f32,
            r: f32,
            g: f32,
            b: f32,
        ) -> *mut BEAM,
    >,
    pub R_BeamEnts: Option<
        unsafe extern "C" fn(
            startEnt: c_int,
            endEnt: c_int,
            modelIndex: c_int,
            life: f32,
            width: f32,
            amplitude: f32,
            brightness: f32,
            speed: f32,
            startFrame: c_int,
            framerate: f32,
            r: f32,
            g: f32,
            b: f32,
        ) -> *mut BEAM,
    >,
    pub R_BeamFollow: Option<
        unsafe extern "C" fn(
            startEnt: c_int,
            modelIndex: c_int,
            life: f32,
            width: f32,
            r: f32,
            g: f32,
            b: f32,
            brightness: f32,
        ) -> *mut BEAM,
    >,
    pub R_BeamKill: Option<unsafe extern "C" fn(deadEntity: c_int)>,
    pub R_BeamLightning: Option<
        unsafe extern "C" fn(
            start: *mut f32,
            end: *mut f32,
            modelIndex: c_int,
            life: f32,
            width: f32,
            amplitude: f32,
            brightness: f32,
            speed: f32,
        ) -> *mut BEAM,
    >,
    pub R_BeamPoints: Option<
        unsafe extern "C" fn(
            start: *const f32,
            end: *const f32,
            modelIndex: c_int,
            life: f32,
            width: f32,
            amplitude: f32,
            brightness: f32,
            speed: f32,
            startFrame: c_int,
            framerate: f32,
            r: f32,
            g: f32,
            b: f32,
        ) -> *mut BEAM,
    >,
    pub R_BeamRing: Option<
        unsafe extern "C" fn(
            startEnt: c_int,
            endEnt: c_int,
            modelIndex: c_int,
            life: f32,
            width: f32,
            amplitude: f32,
            brightness: f32,
            speed: f32,
            startFrame: c_int,
            framerate: f32,
            r: f32,
            g: f32,
            b: f32,
        ) -> *mut BEAM,
    >,
    pub CL_AllocDlight: Option<unsafe extern "C" fn(key: c_int) -> *mut dlight_t>,
    pub CL_AllocElight: Option<unsafe extern "C" fn(key: c_int) -> *mut dlight_t>,
    pub CL_TempEntAlloc:
        Option<unsafe extern "C" fn(org: *mut f32, model: *mut model_s) -> *mut TEMPENTITY>,
    pub CL_TempEntAllocNoModel: Option<unsafe extern "C" fn(org: *mut f32) -> *mut TEMPENTITY>,
    pub CL_TempEntAllocHigh:
        Option<unsafe extern "C" fn(org: *mut f32, model: *mut model_s) -> *mut TEMPENTITY>,
    pub CL_TentEntAllocCustom: Option<
        unsafe extern "C" fn(
            origin: *mut f32,
            model: *mut model_s,
            high: c_int,
            callback: Option<
                unsafe extern "C" fn(ent: *mut tempent_s, frametime: f32, currenttime: f32),
            >,
        ) -> *mut TEMPENTITY,
    >,
    pub R_GetPackedColor: Option<unsafe extern "C" fn(packed: *mut c_short, color: c_short)>,
    pub R_LookupColor: Option<unsafe extern "C" fn(r: c_uchar, g: c_uchar, b: c_uchar) -> c_short>,
    pub R_DecalRemoveAll: Option<unsafe extern "C" fn(textureIndex: c_int)>,
    pub R_FireCustomDecal: Option<
        unsafe extern "C" fn(
            textureIndex: c_int,
            entity: c_int,
            modelIndex: c_int,
            position: *mut f32,
            flags: c_int,
            scale: f32,
        ),
    >,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of efx_api_s"][::std::mem::size_of::<efx_api_s>() - 296usize];
    ["Alignment of efx_api_s"][::std::mem::align_of::<efx_api_s>() - 4usize];
    ["Offset of field: efx_api_s::R_AllocParticle"]
        [::std::mem::offset_of!(efx_api_s, R_AllocParticle) - 0usize];
    ["Offset of field: efx_api_s::R_BlobExplosion"]
        [::std::mem::offset_of!(efx_api_s, R_BlobExplosion) - 4usize];
    ["Offset of field: efx_api_s::R_Blood"][::std::mem::offset_of!(efx_api_s, R_Blood) - 8usize];
    ["Offset of field: efx_api_s::R_BloodSprite"]
        [::std::mem::offset_of!(efx_api_s, R_BloodSprite) - 12usize];
    ["Offset of field: efx_api_s::R_BloodStream"]
        [::std::mem::offset_of!(efx_api_s, R_BloodStream) - 16usize];
    ["Offset of field: efx_api_s::R_BreakModel"]
        [::std::mem::offset_of!(efx_api_s, R_BreakModel) - 20usize];
    ["Offset of field: efx_api_s::R_Bubbles"]
        [::std::mem::offset_of!(efx_api_s, R_Bubbles) - 24usize];
    ["Offset of field: efx_api_s::R_BubbleTrail"]
        [::std::mem::offset_of!(efx_api_s, R_BubbleTrail) - 28usize];
    ["Offset of field: efx_api_s::R_BulletImpactParticles"]
        [::std::mem::offset_of!(efx_api_s, R_BulletImpactParticles) - 32usize];
    ["Offset of field: efx_api_s::R_EntityParticles"]
        [::std::mem::offset_of!(efx_api_s, R_EntityParticles) - 36usize];
    ["Offset of field: efx_api_s::R_Explosion"]
        [::std::mem::offset_of!(efx_api_s, R_Explosion) - 40usize];
    ["Offset of field: efx_api_s::R_FizzEffect"]
        [::std::mem::offset_of!(efx_api_s, R_FizzEffect) - 44usize];
    ["Offset of field: efx_api_s::R_FireField"]
        [::std::mem::offset_of!(efx_api_s, R_FireField) - 48usize];
    ["Offset of field: efx_api_s::R_FlickerParticles"]
        [::std::mem::offset_of!(efx_api_s, R_FlickerParticles) - 52usize];
    ["Offset of field: efx_api_s::R_FunnelSprite"]
        [::std::mem::offset_of!(efx_api_s, R_FunnelSprite) - 56usize];
    ["Offset of field: efx_api_s::R_Implosion"]
        [::std::mem::offset_of!(efx_api_s, R_Implosion) - 60usize];
    ["Offset of field: efx_api_s::R_LargeFunnel"]
        [::std::mem::offset_of!(efx_api_s, R_LargeFunnel) - 64usize];
    ["Offset of field: efx_api_s::R_LavaSplash"]
        [::std::mem::offset_of!(efx_api_s, R_LavaSplash) - 68usize];
    ["Offset of field: efx_api_s::R_MultiGunshot"]
        [::std::mem::offset_of!(efx_api_s, R_MultiGunshot) - 72usize];
    ["Offset of field: efx_api_s::R_MuzzleFlash"]
        [::std::mem::offset_of!(efx_api_s, R_MuzzleFlash) - 76usize];
    ["Offset of field: efx_api_s::R_ParticleBox"]
        [::std::mem::offset_of!(efx_api_s, R_ParticleBox) - 80usize];
    ["Offset of field: efx_api_s::R_ParticleBurst"]
        [::std::mem::offset_of!(efx_api_s, R_ParticleBurst) - 84usize];
    ["Offset of field: efx_api_s::R_ParticleExplosion"]
        [::std::mem::offset_of!(efx_api_s, R_ParticleExplosion) - 88usize];
    ["Offset of field: efx_api_s::R_ParticleExplosion2"]
        [::std::mem::offset_of!(efx_api_s, R_ParticleExplosion2) - 92usize];
    ["Offset of field: efx_api_s::R_ParticleLine"]
        [::std::mem::offset_of!(efx_api_s, R_ParticleLine) - 96usize];
    ["Offset of field: efx_api_s::R_PlayerSprites"]
        [::std::mem::offset_of!(efx_api_s, R_PlayerSprites) - 100usize];
    ["Offset of field: efx_api_s::R_Projectile"]
        [::std::mem::offset_of!(efx_api_s, R_Projectile) - 104usize];
    ["Offset of field: efx_api_s::R_RicochetSound"]
        [::std::mem::offset_of!(efx_api_s, R_RicochetSound) - 108usize];
    ["Offset of field: efx_api_s::R_RicochetSprite"]
        [::std::mem::offset_of!(efx_api_s, R_RicochetSprite) - 112usize];
    ["Offset of field: efx_api_s::R_RocketFlare"]
        [::std::mem::offset_of!(efx_api_s, R_RocketFlare) - 116usize];
    ["Offset of field: efx_api_s::R_RocketTrail"]
        [::std::mem::offset_of!(efx_api_s, R_RocketTrail) - 120usize];
    ["Offset of field: efx_api_s::R_RunParticleEffect"]
        [::std::mem::offset_of!(efx_api_s, R_RunParticleEffect) - 124usize];
    ["Offset of field: efx_api_s::R_ShowLine"]
        [::std::mem::offset_of!(efx_api_s, R_ShowLine) - 128usize];
    ["Offset of field: efx_api_s::R_SparkEffect"]
        [::std::mem::offset_of!(efx_api_s, R_SparkEffect) - 132usize];
    ["Offset of field: efx_api_s::R_SparkShower"]
        [::std::mem::offset_of!(efx_api_s, R_SparkShower) - 136usize];
    ["Offset of field: efx_api_s::R_SparkStreaks"]
        [::std::mem::offset_of!(efx_api_s, R_SparkStreaks) - 140usize];
    ["Offset of field: efx_api_s::R_Spray"][::std::mem::offset_of!(efx_api_s, R_Spray) - 144usize];
    ["Offset of field: efx_api_s::R_Sprite_Explode"]
        [::std::mem::offset_of!(efx_api_s, R_Sprite_Explode) - 148usize];
    ["Offset of field: efx_api_s::R_Sprite_Smoke"]
        [::std::mem::offset_of!(efx_api_s, R_Sprite_Smoke) - 152usize];
    ["Offset of field: efx_api_s::R_Sprite_Spray"]
        [::std::mem::offset_of!(efx_api_s, R_Sprite_Spray) - 156usize];
    ["Offset of field: efx_api_s::R_Sprite_Trail"]
        [::std::mem::offset_of!(efx_api_s, R_Sprite_Trail) - 160usize];
    ["Offset of field: efx_api_s::R_Sprite_WallPuff"]
        [::std::mem::offset_of!(efx_api_s, R_Sprite_WallPuff) - 164usize];
    ["Offset of field: efx_api_s::R_StreakSplash"]
        [::std::mem::offset_of!(efx_api_s, R_StreakSplash) - 168usize];
    ["Offset of field: efx_api_s::R_TracerEffect"]
        [::std::mem::offset_of!(efx_api_s, R_TracerEffect) - 172usize];
    ["Offset of field: efx_api_s::R_UserTracerParticle"]
        [::std::mem::offset_of!(efx_api_s, R_UserTracerParticle) - 176usize];
    ["Offset of field: efx_api_s::R_TracerParticles"]
        [::std::mem::offset_of!(efx_api_s, R_TracerParticles) - 180usize];
    ["Offset of field: efx_api_s::R_TeleportSplash"]
        [::std::mem::offset_of!(efx_api_s, R_TeleportSplash) - 184usize];
    ["Offset of field: efx_api_s::R_TempSphereModel"]
        [::std::mem::offset_of!(efx_api_s, R_TempSphereModel) - 188usize];
    ["Offset of field: efx_api_s::R_TempModel"]
        [::std::mem::offset_of!(efx_api_s, R_TempModel) - 192usize];
    ["Offset of field: efx_api_s::R_DefaultSprite"]
        [::std::mem::offset_of!(efx_api_s, R_DefaultSprite) - 196usize];
    ["Offset of field: efx_api_s::R_TempSprite"]
        [::std::mem::offset_of!(efx_api_s, R_TempSprite) - 200usize];
    ["Offset of field: efx_api_s::Draw_DecalIndex"]
        [::std::mem::offset_of!(efx_api_s, Draw_DecalIndex) - 204usize];
    ["Offset of field: efx_api_s::Draw_DecalIndexFromName"]
        [::std::mem::offset_of!(efx_api_s, Draw_DecalIndexFromName) - 208usize];
    ["Offset of field: efx_api_s::R_DecalShoot"]
        [::std::mem::offset_of!(efx_api_s, R_DecalShoot) - 212usize];
    ["Offset of field: efx_api_s::R_AttachTentToPlayer"]
        [::std::mem::offset_of!(efx_api_s, R_AttachTentToPlayer) - 216usize];
    ["Offset of field: efx_api_s::R_KillAttachedTents"]
        [::std::mem::offset_of!(efx_api_s, R_KillAttachedTents) - 220usize];
    ["Offset of field: efx_api_s::R_BeamCirclePoints"]
        [::std::mem::offset_of!(efx_api_s, R_BeamCirclePoints) - 224usize];
    ["Offset of field: efx_api_s::R_BeamEntPoint"]
        [::std::mem::offset_of!(efx_api_s, R_BeamEntPoint) - 228usize];
    ["Offset of field: efx_api_s::R_BeamEnts"]
        [::std::mem::offset_of!(efx_api_s, R_BeamEnts) - 232usize];
    ["Offset of field: efx_api_s::R_BeamFollow"]
        [::std::mem::offset_of!(efx_api_s, R_BeamFollow) - 236usize];
    ["Offset of field: efx_api_s::R_BeamKill"]
        [::std::mem::offset_of!(efx_api_s, R_BeamKill) - 240usize];
    ["Offset of field: efx_api_s::R_BeamLightning"]
        [::std::mem::offset_of!(efx_api_s, R_BeamLightning) - 244usize];
    ["Offset of field: efx_api_s::R_BeamPoints"]
        [::std::mem::offset_of!(efx_api_s, R_BeamPoints) - 248usize];
    ["Offset of field: efx_api_s::R_BeamRing"]
        [::std::mem::offset_of!(efx_api_s, R_BeamRing) - 252usize];
    ["Offset of field: efx_api_s::CL_AllocDlight"]
        [::std::mem::offset_of!(efx_api_s, CL_AllocDlight) - 256usize];
    ["Offset of field: efx_api_s::CL_AllocElight"]
        [::std::mem::offset_of!(efx_api_s, CL_AllocElight) - 260usize];
    ["Offset of field: efx_api_s::CL_TempEntAlloc"]
        [::std::mem::offset_of!(efx_api_s, CL_TempEntAlloc) - 264usize];
    ["Offset of field: efx_api_s::CL_TempEntAllocNoModel"]
        [::std::mem::offset_of!(efx_api_s, CL_TempEntAllocNoModel) - 268usize];
    ["Offset of field: efx_api_s::CL_TempEntAllocHigh"]
        [::std::mem::offset_of!(efx_api_s, CL_TempEntAllocHigh) - 272usize];
    ["Offset of field: efx_api_s::CL_TentEntAllocCustom"]
        [::std::mem::offset_of!(efx_api_s, CL_TentEntAllocCustom) - 276usize];
    ["Offset of field: efx_api_s::R_GetPackedColor"]
        [::std::mem::offset_of!(efx_api_s, R_GetPackedColor) - 280usize];
    ["Offset of field: efx_api_s::R_LookupColor"]
        [::std::mem::offset_of!(efx_api_s, R_LookupColor) - 284usize];
    ["Offset of field: efx_api_s::R_DecalRemoveAll"]
        [::std::mem::offset_of!(efx_api_s, R_DecalRemoveAll) - 288usize];
    ["Offset of field: efx_api_s::R_FireCustomDecal"]
        [::std::mem::offset_of!(efx_api_s, R_FireCustomDecal) - 292usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mleaf_s {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mnode_s {
    pub _address: u8,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct pmtrace_s {
    _unused: [u8; 0],
}
